<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\..\..\neofs-api-csharp\src\Neo.FileStorage.API\Neo.FileStorage.API.csproj" />
		<ProjectReference Include="..\..\src\Neo.ConsoleService\Neo.ConsoleService.csproj" />
		<ProjectReference Include="..\RpcServer\RpcServer.csproj">
			<Private>false</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="OracleService.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Neo.Plugins.OracleService.Tests" />
	</ItemGroup>

</Project>
