// Copyright (C) 2015-2026 The Neo Project.
//
// NefCSharpWriter.cs file belongs to the neo project and is free
// software distributed under the MIT software license, see the
// accompanying file LICENSE in the main directory of the
// repository or http://www.opensource.org/licenses/mit-license.php
// for more details.
//
// Redistribution and use in source and binary forms with or without
// modifications are permitted.

using Neo.SmartContract;
using Neo.VM;
using System.Globalization;
using System.Numerics;
using System.Text;
using System.Text.Unicode;

namespace Neo.CLI;

/// <summary>
/// Turns a <see cref="NefFile"/> script into C# pseudocode (stack machine).
/// </summary>
internal static class NefCSharpWriter
{
    public static string Generate(NefFile nef, string className)
    {
        ArgumentNullException.ThrowIfNull(nef);
        ArgumentException.ThrowIfNullOrWhiteSpace(className);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// C# pseudocode generated from NEF");
        sb.AppendLine($"// Compiler: {EscapeComment(nef.Compiler)}");
        if (!string.IsNullOrEmpty(nef.Source))
            sb.AppendLine($"// Source: {EscapeComment(nef.Source)}");
        sb.AppendLine($"// Checksum: 0x{nef.CheckSum:X8}");
        sb.AppendLine($"// Script length: {nef.Script.Length} bytes");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Numerics;");
        sb.AppendLine();
        sb.AppendLine("namespace Neo.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    public static void Execute()");
        sb.AppendLine("    {");
        sb.AppendLine("        var stack = new Stack<object?>();");
        sb.AppendLine();

        foreach (var ins in new VMInstruction(nef.Script))
        {
            sb.AppendLine($"        {Label(ins.Position)}:");
            foreach (var stmt in Emit(ins, nef.Tokens))
                sb.AppendLine($"            {stmt}");
        }

        sb.AppendLine();
        sb.AppendLine("        static bool IsTrue(object? value)");
        sb.AppendLine("            => value switch");
        sb.AppendLine("            {");
        sb.AppendLine("                null => false,");
        sb.AppendLine("                bool b => b,");
        sb.AppendLine("                BigInteger n => n != 0,");
        sb.AppendLine("                _ => true,");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("        static void Bin(Func<object?, object?, object?> op)");
        sb.AppendLine("        {");
        sb.AppendLine("            var a = stack.Pop();");
        sb.AppendLine("            var b = stack.Pop();");
        sb.AppendLine("            stack.Push(op(a, b));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        static void Pack(Stack<object?> s)");
        sb.AppendLine("        {");
        sb.AppendLine("            var n = Convert.ToInt32(s.Pop());");
        sb.AppendLine("            var items = new object?[n];");
        sb.AppendLine("            for (var i = n - 1; i >= 0; i--)");
        sb.AppendLine("                items[i] = s.Pop();");
        sb.AppendLine("            s.Push(items);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        static void Unpack(Stack<object?> s)");
        sb.AppendLine("        {");
        sb.AppendLine("            var items = (IList<object?>)s.Pop()!;");
        sb.AppendLine("            foreach (var item in items)");
        sb.AppendLine("                s.Push(item);");
        sb.AppendLine("            s.Push(items.Count);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string ToClassName(string nefPath)
    {
        var name = Path.GetFileNameWithoutExtension(nefPath);
        var sb = new StringBuilder();
        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }

        if (sb.Length == 0 || char.IsDigit(sb[0]))
            sb.Insert(0, '_');
        return sb.ToString();
    }

    private static string Label(int position)
        => $"L_{position.ToString("X4", CultureInfo.InvariantCulture)}";

    private static IEnumerable<string> Emit(VMInstruction ins, MethodToken[] tokens)
    {
        var op = ins.OpCode;
        var operand = ins.Operand[ins.OperandPrefixSize..].ToArray();

        switch (op)
        {
            case OpCode.NOP:
                yield return "// NOP";
                yield break;
            case OpCode.RET:
                yield return "return;";
                yield break;
            case OpCode.ABORT:
                yield return "throw new Exception(\"ABORT\");";
                yield break;
            case OpCode.ABORTMSG:
                yield return "throw new Exception(stack.Pop()?.ToString() ?? \"ABORTMSG\");";
                yield break;
            case OpCode.ASSERT:
                yield return "if (!IsTrue(stack.Pop())) throw new Exception(\"ASSERT\");";
                yield break;
            case OpCode.THROW:
                yield return "throw new Exception(stack.Pop()?.ToString());";
                yield break;

            case OpCode.PUSH0:
            case OpCode.PUSH1:
            case OpCode.PUSH2:
            case OpCode.PUSH3:
            case OpCode.PUSH4:
            case OpCode.PUSH5:
            case OpCode.PUSH6:
            case OpCode.PUSH7:
            case OpCode.PUSH8:
            case OpCode.PUSH9:
            case OpCode.PUSH10:
            case OpCode.PUSH11:
            case OpCode.PUSH12:
            case OpCode.PUSH13:
            case OpCode.PUSH14:
            case OpCode.PUSH15:
            case OpCode.PUSH16:
                yield return $"stack.Push({(int)op - (int)OpCode.PUSH0}); // {op}";
                yield break;
            case OpCode.PUSHM1:
                yield return "stack.Push(-1);";
                yield break;
            case OpCode.PUSHNULL:
                yield return "stack.Push(null);";
                yield break;
            case OpCode.PUSHT:
                yield return "stack.Push(true);";
                yield break;
            case OpCode.PUSHF:
                yield return "stack.Push(false);";
                yield break;
            case OpCode.PUSHINT8:
                yield return $"stack.Push({ins.AsToken<sbyte>()}); // {op}";
                yield break;
            case OpCode.PUSHINT16:
                yield return $"stack.Push({ins.AsToken<short>()}); // {op}";
                yield break;
            case OpCode.PUSHINT32:
                yield return $"stack.Push({ins.AsToken<int>()}); // {op}";
                yield break;
            case OpCode.PUSHINT64:
                yield return $"stack.Push({ins.AsToken<long>()}L); // {op}";
                yield break;
            case OpCode.PUSHINT128:
            case OpCode.PUSHINT256:
                yield return $"stack.Push(BigInteger.Parse(\"{new BigInteger(operand)}\")); // {op}";
                yield break;
            case OpCode.PUSHDATA1:
            case OpCode.PUSHDATA2:
            case OpCode.PUSHDATA4:
                yield return EmitPushData(operand);
                yield break;

            case OpCode.DUP:
                yield return "stack.Push(stack.Peek()); // DUP";
                yield break;
            case OpCode.DROP:
                yield return "stack.Pop(); // DROP";
                yield break;
            case OpCode.NIP:
                yield return "{ var top = stack.Pop(); stack.Pop(); stack.Push(top); } // NIP";
                yield break;
            case OpCode.OVER:
                yield return "{ var a = stack.Pop(); var b = stack.Peek(); stack.Push(a); stack.Push(b); } // OVER";
                yield break;
            case OpCode.SWAP:
                yield return "{ var a = stack.Pop(); var b = stack.Pop(); stack.Push(a); stack.Push(b); } // SWAP";
                yield break;
            case OpCode.TUCK:
                yield return "{ var a = stack.Pop(); var b = stack.Pop(); stack.Push(a); stack.Push(b); stack.Push(a); } // TUCK";
                yield break;
            case OpCode.ROT:
                yield return "{ var a = stack.Pop(); var b = stack.Pop(); var c = stack.Pop(); stack.Push(b); stack.Push(a); stack.Push(c); } // ROT";
                yield break;
            case OpCode.PICK:
                yield return "// PICK n: duplicate stack[n]";
                yield return "stack.Pop();";
                yield break;
            case OpCode.ROLL:
                yield return "// ROLL n";
                yield return "stack.Pop();";
                yield break;
            case OpCode.REVERSE3:
                yield return "// REVERSE3";
                yield break;
            case OpCode.REVERSE4:
                yield return "// REVERSE4";
                yield break;
            case OpCode.REVERSEN:
                yield return "// REVERSEN";
                yield return "stack.Pop();";
                yield break;
            case OpCode.DEPTH:
                yield return "stack.Push(stack.Count); // DEPTH";
                yield break;
            case OpCode.CLEAR:
                yield return "stack.Clear();";
                yield break;

            case OpCode.ADD:
                yield return "Bin((a, b) => (BigInteger)b! + (BigInteger)a!); // ADD";
                yield break;
            case OpCode.SUB:
                yield return "Bin((a, b) => (BigInteger)b! - (BigInteger)a!); // SUB";
                yield break;
            case OpCode.MUL:
                yield return "Bin((a, b) => (BigInteger)b! * (BigInteger)a!); // MUL";
                yield break;
            case OpCode.DIV:
                yield return "Bin((a, b) => (BigInteger)b! / (BigInteger)a!); // DIV";
                yield break;
            case OpCode.MOD:
                yield return "Bin((a, b) => (BigInteger)b! % (BigInteger)a!); // MOD";
                yield break;
            case OpCode.POW:
                yield return "Bin((a, b) => BigInteger.Pow((BigInteger)b!, (int)(BigInteger)a!)); // POW";
                yield break;
            case OpCode.INC:
                yield return "stack.Push((BigInteger)stack.Pop()! + 1); // INC";
                yield break;
            case OpCode.DEC:
                yield return "stack.Push((BigInteger)stack.Pop()! - 1); // DEC";
                yield break;
            case OpCode.NEGATE:
                yield return "stack.Push(-(BigInteger)stack.Pop()!); // NEGATE";
                yield break;
            case OpCode.ABS:
                yield return "stack.Push(BigInteger.Abs((BigInteger)stack.Pop()!)); // ABS";
                yield break;
            case OpCode.SIGN:
                yield return "stack.Push(((BigInteger)stack.Pop()!).Sign); // SIGN";
                yield break;
            case OpCode.NOT:
                yield return "stack.Push(!IsTrue(stack.Pop())); // NOT";
                yield break;
            case OpCode.NZ:
                yield return "stack.Push((BigInteger)stack.Pop()! != 0); // NZ";
                yield break;
            case OpCode.EQUAL:
            case OpCode.NOTEQUAL:
            case OpCode.LT:
            case OpCode.LE:
            case OpCode.GT:
            case OpCode.GE:
            case OpCode.NUMEQUAL:
            case OpCode.NUMNOTEQUAL:
            case OpCode.MIN:
            case OpCode.MAX:
            case OpCode.BOOLAND:
            case OpCode.BOOLOR:
            case OpCode.AND:
            case OpCode.OR:
            case OpCode.XOR:
            case OpCode.SHL:
            case OpCode.SHR:
                yield return $"Bin((a, b) => default); // {op} (b, a)";
                yield break;
            case OpCode.INVERT:
                yield return "stack.Push(~(BigInteger)stack.Pop()!); // INVERT";
                yield break;

            case OpCode.CAT:
                yield return "// CAT";
                yield return "stack.Pop(); stack.Pop();";
                yield break;
            case OpCode.SIZE:
                yield return "// SIZE";
                yield break;
            case OpCode.PACK:
                yield return "Pack(stack); // PACK";
                yield break;
            case OpCode.UNPACK:
                yield return "Unpack(stack); // UNPACK";
                yield break;
            case OpCode.NEWARRAY0:
            case OpCode.NEWSTRUCT0:
                yield return $"stack.Push(new List<object?>()); // {op}";
                yield break;
            case OpCode.NEWARRAY:
            case OpCode.NEWARRAY_T:
            case OpCode.NEWSTRUCT:
                yield return $"stack.Push(new List<object?>(Convert.ToInt32(stack.Pop()))); // {op}";
                yield break;
            case OpCode.NEWMAP:
                yield return "stack.Push(new Dictionary<object, object?>()); // NEWMAP";
                yield break;
            case OpCode.APPEND:
                yield return "// APPEND";
                yield return "stack.Pop(); stack.Pop();";
                yield break;
            case OpCode.SETITEM:
                yield return "// SETITEM";
                yield return "stack.Pop(); stack.Pop(); stack.Pop();";
                yield break;
            case OpCode.PICKITEM:
                yield return "// PICKITEM";
                yield return "stack.Pop(); stack.Pop();";
                yield break;
            case OpCode.REMOVE:
            case OpCode.CLEARITEMS:
            case OpCode.POPITEM:
            case OpCode.KEYS:
            case OpCode.VALUES:
            case OpCode.HASKEY:
            case OpCode.ISNULL:
                yield return $"// {op}";
                yield break;

            case OpCode.JMP:
            case OpCode.JMP_L:
                yield return $"goto {Label(JumpTarget(ins))}; // {op}";
                yield break;
            case OpCode.JMPIF:
            case OpCode.JMPIF_L:
                yield return $"if (IsTrue(stack.Pop())) goto {Label(JumpTarget(ins))}; // {op}";
                yield break;
            case OpCode.JMPIFNOT:
            case OpCode.JMPIFNOT_L:
                yield return $"if (!IsTrue(stack.Pop())) goto {Label(JumpTarget(ins))}; // {op}";
                yield break;
            case OpCode.JMPEQ:
            case OpCode.JMPNE:
            case OpCode.JMPGT:
            case OpCode.JMPLT:
            case OpCode.JMPGE:
            case OpCode.JMPLE:
            case OpCode.JMPEQ_L:
            case OpCode.JMPNE_L:
            case OpCode.JMPGT_L:
            case OpCode.JMPLT_L:
            case OpCode.JMPGE_L:
            case OpCode.JMPLE_L:
                yield return $"stack.Pop(); stack.Pop(); goto {Label(JumpTarget(ins))}; // {op} (condition omitted)";
                yield break;
            case OpCode.CALL:
            case OpCode.CALL_L:
                yield return $"{Label(JumpTarget(ins))}(); // {op} (pseudocode call)";
                yield break;
            case OpCode.CALLA:
                yield return "// CALLA";
                yield break;
            case OpCode.CALLT:
                {
                    var index = ins.AsToken<ushort>();
                    var name = index < tokens.Length ? tokens[index].Method : index.ToString(CultureInfo.InvariantCulture);
                    yield return $"// CALLT [{index}] {name}";
                    yield break;
                }
            case OpCode.PUSHA:
                yield return $"stack.Push(\"{Label(JumpTarget(ins))}\"); // PUSHA";
                yield break;
            case OpCode.TRY:
            case OpCode.TRY_L:
                yield return $"// {op} {ins.DecodeOperand()}";
                yield break;
            case OpCode.ENDTRY:
            case OpCode.ENDTRY_L:
            case OpCode.ENDFINALLY:
                yield return $"// {op}";
                yield break;

            case OpCode.SYSCALL:
                {
                    var hash = BitConverter.ToUInt32(operand, 0);
                    var service = ApplicationEngine.Services.TryGetValue(hash, out var s) ? s.Name : $"0x{hash:X8}";
                    yield return $"// SYSCALL {service}";
                    yield break;
                }

            case OpCode.INITSLOT:
                yield return $"// INITSLOT locals={ins.AsToken<byte>()} args={ins.AsToken<byte>(1)}";
                yield break;
            case OpCode.INITSSLOT:
                yield return $"// INITSSLOT static={ins.AsToken<byte>()}";
                yield break;
            case OpCode.LDARG:
            case OpCode.STARG:
            case OpCode.LDLOC:
            case OpCode.STLOC:
            case OpCode.LDSFLD:
            case OpCode.STSFLD:
                yield return $"// {op} {ins.AsToken<byte>()}";
                yield break;
            case OpCode.CONVERT:
            case OpCode.ISTYPE:
            case OpCode.NEWBUFFER:
            case OpCode.MEMCPY:
            case OpCode.LEFT:
            case OpCode.RIGHT:
            case OpCode.SUBSTR:
            default:
                yield return $"// {op} {ins.DecodeOperand()}".TrimEnd();
                yield break;
        }
    }

    private static string EmitPushData(byte[] data)
    {
        if (TryUtf8Literal(data, out var text))
            return $"stack.Push(\"{EscapeCSharp(text)}\");";

        var hex = Convert.ToHexString(data);
        return $"stack.Push(Convert.FromHexString(\"{hex}\")); // blob {data.Length} bytes";
    }

    private static bool TryUtf8Literal(byte[] data, out string text)
    {
        text = null!;
        if (data.Length == 0 || !Utf8.IsValid(data))
            return false;
        text = Encoding.UTF8.GetString(data);
        foreach (var rune in text.EnumerateRunes())
        {
            if (Rune.IsControl(rune))
                return false;
        }
        return true;
    }

    private static int JumpTarget(VMInstruction ins)
    {
        var data = ins.Operand[ins.OperandPrefixSize..].ToArray();
        var offset = data.Length switch
        {
            1 => (int)(sbyte)data[0],
            4 => BitConverter.ToInt32(data, 0),
            _ => 0,
        };
        return ins.Position + offset;
    }

    private static string EscapeCSharp(string value)
        => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

    private static string EscapeComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ');
}
