name: Docker Build Test

on: pull_request

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Build-Test
      run: |
        docker buildx build \
          --no-cache \
          --tag ghcr.io/neo-project/neo-node:latest \
          --platform linux/amd64,linux/arm64 \
          ./